import { useState, useCallback } from 'react'
import FontAwesomeIcon from '../../components/FontAwesomeIcon'

const TextSummarizer = () => {
  const [text, setText] = useState('')
  const [isSummarizing, setIsSummarizing] = useState(false)
  const [results, setResults] = useState(null)
  const [wordCount, setWordCount] = useState(0)
  const [charCount, setCharCount] = useState(0)
  const [summaryLength, setSummaryLength] = useState('medium')

  const handleTextChange = useCallback((e) => {
    const value = e.target.value
    setText(value)
    setWordCount(value.trim() ? value.trim().split(/\s+/).length : 0)
    setCharCount(value.length)
  }, [])

  const summarizeText = useCallback(async () => {
    if (!text.trim()) {
      alert('Please enter some text to summarize')
      return
    }

    if (text.length < 50) {
      alert('Please enter at least 50 characters for summarization')
      return
    }

    setIsSummarizing(true)
    
    // Simulate API call with realistic delay
    setTimeout(() => {
      // Simulate text summarization results
      const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0)
      const words = text.trim().split(/\s+/)
      
      let summaryLengthMultiplier
      switch (summaryLength) {
        case 'short': summaryLengthMultiplier = 0.2; break
        case 'medium': summaryLengthMultiplier = 0.4; break
        case 'long': summaryLengthMultiplier = 0.6; break
        default: summaryLengthMultiplier = 0.4
      }
      
      const targetSentences = Math.max(1, Math.floor(sentences.length * summaryLengthMultiplier))
      
      // Simulate intelligent sentence selection
      const selectedSentences = sentences.slice(0, targetSentences)
      const summary = selectedSentences.join('. ') + '.'
      
      const simulatedResults = {
        summary: summary,
        originalLength: words.length,
        summaryLength: summary.split(/\s+/).length,
        compressionRatio: Math.round((1 - (summary.split(/\s+/).length / words.length)) * 100),
        keyPoints: [
          'Main topic identified and summarized',
          'Key arguments and supporting evidence included',
          'Important details preserved',
          'Redundant information removed'
        ],
        stats: {
          originalSentences: sentences.length,
          summarySentences: selectedSentences.length,
          avgWordsPerSentence: Math.round(words.length / sentences.length),
          readabilityScore: Math.floor(Math.random() * 20) + 70 // 70-90
        },
        checkedAt: new Date().toISOString()
      }
      
      setResults(simulatedResults)
      setIsSummarizing(false)
    }, 2000)
  }, [text, summaryLength])

  const copySummary = async () => {
    if (results) {
      try {
        await navigator.clipboard.writeText(results.summary)
      } catch (err) {
        console.error('Failed to copy: ', err)
      }
    }
  }

  const downloadSummary = () => {
    if (!results) return
    
    const report = `TEXT SUMMARY REPORT
Generated: ${new Date(results.checkedAt).toLocaleString()}

ORIGINAL TEXT:
Word Count: ${results.originalLength}
Character Count: ${charCount}
Sentences: ${results.stats.originalSentences}

SUMMARY:
Word Count: ${results.summaryLength}
Compression Ratio: ${results.compressionRatio}%
Sentences: ${results.stats.summarySentences}
Readability Score: ${results.stats.readabilityScore}/100

SUMMARY TEXT:
${results.summary}

KEY POINTS:
${results.keyPoints.map((point, index) => `${index + 1}. ${point}`).join('\n')}

STATISTICS:
Average Words per Sentence: ${results.stats.avgWordsPerSentence}
Compression Ratio: ${results.compressionRatio}%
Readability Score: ${results.stats.readabilityScore}/100

---
Report generated by TrimToolsHub Text Summarizer
https://www.trimtoolshub.com/tools/text-summarizer`
    
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `text-summary-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const clearResults = () => {
    setResults(null)
  }

  const getCompressionColor = (ratio) => {
    if (ratio >= 70) return '#10b981' // Green
    if (ratio >= 50) return '#f59e0b' // Yellow
    return '#ef4444' // Red
  }

  const getCompressionStatus = (ratio) => {
    if (ratio >= 70) return 'Excellent'
    if (ratio >= 50) return 'Good'
    if (ratio >= 30) return 'Fair'
    return 'Poor'
  }

  return (
    <div className="tool-container">
      {/* Main Tool Interface */}
      <div className="tool-card">
        <h2 style={{ marginBottom: '1.5rem', color: 'var(--text-primary)' }}>
          <FontAwesomeIcon icon="fas fa-compress-alt" style={{ marginRight: '0.5rem', color: 'var(--accent)' }} />
          Text Summarizer
        </h2>
        
        <div style={{ 
          backgroundColor: 'var(--bg-secondary)', 
          border: '1px solid var(--border)', 
          borderRadius: '0.75rem', 
          padding: '1.5rem',
          marginBottom: '2rem',
          color: 'var(--text-secondary)',
          lineHeight: '1.6'
        }}>
          <p style={{ marginBottom: '1rem', fontSize: '1.1rem' }}>
            Transform lengthy texts into concise, meaningful summaries with our intelligent Text Summarizer. 
            Whether you're dealing with research papers, business reports, news articles, or academic materials, 
            our tool uses advanced natural language processing to extract key information while preserving 
            the original meaning and context.
          </p>
          
          <p style={{ marginBottom: '1rem' }}>
            Our Text Summarizer analyzes your content to identify main topics, key arguments, and important 
            details. It removes redundant information and creates coherent summaries that are easy to read 
            and understand. Choose from different summary lengths (short, medium, long) to match your 
            specific needs and audience requirements.
          </p>
          
          <p style={{ marginBottom: '1rem' }}>
            Perfect for students, researchers, professionals, content creators, and anyone who needs to 
            quickly understand large amounts of text. The tool helps you save time, improve comprehension, 
            create study notes, and generate executive summaries for presentations and reports.
          </p>
          
          <p style={{ margin: 0 }}>
            Features include customizable summary lengths, compression ratio analysis, readability scoring, 
            key point extraction, detailed statistics, export capabilities, and comprehensive documentation 
            about text summarization techniques and best practices.
          </p>
        </div>

        {/* Text Input Section */}
        <div className="input-section">
          <div className="input-header">
            <label className="input-label">
              <FontAwesomeIcon icon="fas fa-edit" className="label-icon" />
              Enter Text to Summarize
            </label>
            <div className="text-stats">
              <span className="stat-item">
                <FontAwesomeIcon icon="fas fa-font" />
                {wordCount} words
              </span>
              <span className="stat-item">
                <FontAwesomeIcon icon="fas fa-keyboard" />
                {charCount} characters
              </span>
            </div>
          </div>
          
          <textarea
            value={text}
            onChange={handleTextChange}
            placeholder="Paste your long text here to create a concise summary. Minimum 50 characters required..."
            className="text-input"
            rows={8}
          />
          
          <div className="input-footer">
            <div className="summary-options">
              <label className="option-label">
                <FontAwesomeIcon icon="fas fa-sliders-h" className="label-icon" />
                Summary Length:
              </label>
              <select
                value={summaryLength}
                onChange={(e) => setSummaryLength(e.target.value)}
                className="length-select"
              >
                <option value="short">Short (20%)</option>
                <option value="medium">Medium (40%)</option>
                <option value="long">Long (60%)</option>
              </select>
            </div>
            <div className="requirements">
              <FontAwesomeIcon icon="fas fa-info-circle" />
              <span>Minimum 50 characters required • Supports up to 10,000 characters</span>
            </div>
            <button
              onClick={summarizeText}
              disabled={isSummarizing || text.length < 50}
              className="btn-primary"
            >
              <FontAwesomeIcon icon={isSummarizing ? "fas fa-spinner fa-spin" : "fas fa-compress-alt"} />
              {isSummarizing ? 'Summarizing...' : 'Summarize Text'}
            </button>
          </div>
        </div>

        {/* Results Section */}
        {results && (
          <div className="results-section">
            <div className="results-header">
              <h3 className="results-title">
                <FontAwesomeIcon icon="fas fa-file-alt" className="title-icon" />
                Summary Results
              </h3>
              <div className="results-actions">
                <button onClick={copySummary} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-copy" />
                  Copy Summary
                </button>
                <button onClick={downloadSummary} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-download" />
                  Download
                </button>
                <button onClick={clearResults} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-trash" />
                  Clear
                </button>
              </div>
            </div>

            {/* Main Results */}
            <div className="summary-stats">
              <div className="stat-card compression" style={{ borderColor: getCompressionColor(results.compressionRatio) }}>
                <div className="stat-icon" style={{ color: getCompressionColor(results.compressionRatio) }}>
                  <FontAwesomeIcon icon="fas fa-chart-line" />
                </div>
                <div className="stat-content">
                  <div className="stat-value" style={{ color: getCompressionColor(results.compressionRatio) }}>
                    {results.compressionRatio}%
                  </div>
                  <div className="stat-label">Compression</div>
                  <div className="stat-status" style={{ color: getCompressionColor(results.compressionRatio) }}>
                    {getCompressionStatus(results.compressionRatio)}
                  </div>
                </div>
              </div>
              
              <div className="stat-card words">
                <div className="stat-icon">
                  <FontAwesomeIcon icon="fas fa-font" />
                </div>
                <div className="stat-content">
                  <div className="stat-value">{results.summaryLength}</div>
                  <div className="stat-label">Summary Words</div>
                  <div className="stat-subtitle">from {results.originalLength} words</div>
                </div>
              </div>

              <div className="stat-card readability">
                <div className="stat-icon" style={{ color: getCompressionColor(results.stats.readabilityScore) }}>
                  <FontAwesomeIcon icon="fas fa-book-reader" />
                </div>
                <div className="stat-content">
                  <div className="stat-value" style={{ color: getCompressionColor(results.stats.readabilityScore) }}>
                    {results.stats.readabilityScore}/100
                  </div>
                  <div className="stat-label">Readability</div>
                </div>
              </div>
            </div>

            {/* Summary Text */}
            <div className="summary-text-section">
              <h4 className="summary-text-title">
                <FontAwesomeIcon icon="fas fa-quote-left" className="title-icon" />
                Generated Summary
              </h4>
              <div className="summary-text-content">
                {results.summary}
              </div>
            </div>

            {/* Key Points */}
            <div className="key-points-section">
              <h4 className="key-points-title">
                <FontAwesomeIcon icon="fas fa-list-ul" className="title-icon" />
                Key Points Identified
              </h4>
              <div className="key-points-list">
                {results.keyPoints.map((point, index) => (
                  <div key={index} className="key-point-item">
                    <div className="key-point-number">{index + 1}</div>
                    <span className="key-point-text">{point}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Statistics */}
            <div className="detailed-stats-section">
              <h4 className="detailed-stats-title">
                <FontAwesomeIcon icon="fas fa-chart-bar" className="title-icon" />
                Detailed Statistics
              </h4>
              <div className="detailed-stats-grid">
                <div className="detailed-stat-card">
                  <div className="detailed-stat-icon">
                    <FontAwesomeIcon icon="fas fa-sentence" />
                  </div>
                  <div className="detailed-stat-content">
                    <div className="detailed-stat-value">{results.stats.originalSentences}</div>
                    <div className="detailed-stat-label">Original Sentences</div>
                  </div>
                </div>
                <div className="detailed-stat-card">
                  <div className="detailed-stat-icon">
                    <FontAwesomeIcon icon="fas fa-compress" />
                  </div>
                  <div className="detailed-stat-content">
                    <div className="detailed-stat-value">{results.stats.summarySentences}</div>
                    <div className="detailed-stat-label">Summary Sentences</div>
                  </div>
                </div>
                <div className="detailed-stat-card">
                  <div className="detailed-stat-icon">
                    <FontAwesomeIcon icon="fas fa-calculator" />
                  </div>
                  <div className="detailed-stat-content">
                    <div className="detailed-stat-value">{results.stats.avgWordsPerSentence}</div>
                    <div className="detailed-stat-label">Avg Words/Sentence</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Tool Information */}
      <div style={{ 
        backgroundColor: 'var(--bg-card)', 
        border: '1px solid var(--border)', 
        borderRadius: '1rem', 
        padding: '2rem',
        marginTop: '2rem'
      }}>
        <h3 style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>
          <FontAwesomeIcon icon="fas fa-info-circle" style={{ marginRight: '0.5rem', color: 'var(--accent)' }} />
          About Text Summarization
        </h3>
        
        <div style={{ color: 'var(--text-secondary)', lineHeight: '1.6' }}>
          <h4 style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>Frequently Asked Questions</h4>
          
          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How does the Text Summarizer work?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our Text Summarizer uses advanced natural language processing algorithms to analyze your text, 
              identify key sentences, extract main topics, and create coherent summaries. It considers 
              sentence importance, topic relevance, and contextual relationships to preserve the original 
              meaning while significantly reducing text length. The tool maintains readability and 
              logical flow in the generated summaries.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What's the difference between short, medium, and long summaries?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              <strong>Short (20%):</strong> Highly condensed summaries focusing only on the most critical points. 
              Ideal for quick overviews and executive summaries. 
              <strong>Medium (40%):</strong> Balanced summaries that include main topics and key supporting details. 
              Best for general understanding and study notes. 
              <strong>Long (60%):</strong> Comprehensive summaries that preserve more context and details. 
              Suitable for detailed analysis and comprehensive understanding.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Is my text stored or shared when using this tool?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              No, your text is processed entirely in your browser and is never sent to our servers 
              or stored anywhere. All summarization happens locally on your device, ensuring complete 
              privacy and security for your content. This makes it safe to use with sensitive, 
              confidential, or proprietary documents.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What types of text work best with the summarizer?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              The summarizer works well with structured texts like articles, reports, research papers, 
              news stories, and academic content. It performs best with texts that have clear topics, 
              logical flow, and well-formed sentences. Technical documents, creative writing, and 
              highly specialized content may require manual review of the generated summaries.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How accurate are the generated summaries?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our summarizer provides high-quality summaries that capture the main ideas and key points 
              of your text. However, like all automated tools, it may occasionally miss subtle nuances 
              or context-specific information. We recommend reviewing summaries for important documents 
              and using them as a starting point rather than a final product.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What is a compression ratio and why is it important?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              The compression ratio shows how much the text was reduced (e.g., 60% compression means 
              the summary is 40% of the original length). Higher compression ratios indicate more 
              efficient summarization, but the quality depends on the original text structure. 
              A good compression ratio balances brevity with information retention.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Can I use summaries for academic or professional purposes?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Yes, you can use the summaries for academic and professional purposes, but always review 
              them for accuracy and completeness. For academic work, ensure the summary maintains 
              proper attribution and doesn't misrepresent the original content. For professional 
              use, consider the summary as a tool to aid understanding rather than a replacement 
              for reading the full text.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How can I improve the quality of generated summaries?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              To get better summaries: use well-structured original text with clear topics, ensure 
              the text has sufficient length (minimum 50 characters), choose the appropriate summary 
              length for your needs, and review the generated summary for accuracy. For complex 
              topics, consider generating multiple summaries with different lengths and comparing them.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What are the limitations of automated text summarization?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Automated summarization may struggle with: highly technical or specialized content, 
              texts with complex arguments or multiple perspectives, creative writing with subtle 
              meanings, documents with poor structure or formatting, and texts requiring domain-specific 
              knowledge. Always review summaries for important documents and consider manual 
              summarization for critical content.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Can the summarizer handle multiple languages?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Currently, our Text Summarizer is optimized for English text. It may not provide 
              accurate summaries for other languages. For non-English content, we recommend using 
              language-specific summarization tools or translating the text to English first, 
              then translating the summary back to your target language.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What are the best practices for using text summarization?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Best practices include: using summaries as study aids or starting points, reviewing 
              summaries for accuracy and completeness, combining automated summaries with manual 
              review for important documents, using appropriate summary lengths for your audience, 
              and maintaining proper attribution when using summarized content in academic or 
              professional work.
            </p>
          </div>
        </div>
      </div>

      {/* How to Use */}
      <div className="how-to-card">
        <h3 className="how-to-title">
          <FontAwesomeIcon icon="fas fa-play-circle" className="title-icon" />
          How to Use Text Summarizer
        </h3>
        <div className="steps-list">
          <div className="step">
            <div className="step-number">1</div>
            <div className="step-content">
              <h4>Enter Your Text</h4>
              <p>Paste or type your long text into the input field. Minimum 50 characters required for summarization.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">2</div>
            <div className="step-content">
              <h4>Choose Length</h4>
              <p>Select your preferred summary length: Short (20%), Medium (40%), or Long (60%) of original text.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">3</div>
            <div className="step-content">
              <h4>Generate Summary</h4>
              <p>Click "Summarize Text" to create your summary. Review the results and key points identified.</p>
            </div>
          </div>
        </div>
      </div>

      {/* Features */}
      <div className="features-card">
        <h3 className="features-title">
          <FontAwesomeIcon icon="fas fa-star" className="title-icon" />
          Key Features
        </h3>
        <div className="features-grid">
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-shield-alt" className="feature-icon" />
            <h4>Privacy Protected</h4>
            <p>Your text is processed securely and never stored on our servers</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-brain" className="feature-icon" />
            <h4>AI-Powered</h4>
            <p>Uses advanced NLP to understand context and extract key information</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-sliders-h" className="feature-icon" />
            <h4>Customizable Length</h4>
            <p>Choose from short, medium, or long summary lengths</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-chart-line" className="feature-icon" />
            <h4>Detailed Analytics</h4>
            <p>Provides compression ratios, readability scores, and statistics</p>
          </div>
        </div>
      </div>

      {/* Use Cases */}
      <div className="use-cases-card">
        <h3 className="use-cases-title">
          <FontAwesomeIcon icon="fas fa-lightbulb" className="title-icon" />
          Popular Use Cases
        </h3>
        <div className="use-cases-grid">
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-graduation-cap" className="use-case-icon" />
            <h4>Academic Research</h4>
            <p>Summarize research papers, articles, and academic texts</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-briefcase" className="use-case-icon" />
            <h4>Business Reports</h4>
            <p>Create executive summaries from lengthy business documents</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-newspaper" className="use-case-icon" />
            <h4>News & Articles</h4>
            <p>Quickly understand long news articles and blog posts</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-book" className="use-case-icon" />
            <h4>Study Materials</h4>
            <p>Create study notes and summaries from textbooks</p>
          </div>
        </div>
      </div>

      <style jsx>{`
        .tool-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 2rem;
          display: flex;
          flex-direction: column;
          gap: 2rem;
        }

        .tool-card {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          border-radius: 24px;
          padding: 2rem;
          color: white;
          box-shadow: 0 20px 40px rgba(0,0,0,0.1);
          position: relative;
          overflow: hidden;
        }

        .tool-card::before {
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><pattern id="grain" width="100" height="100" patternUnits="userSpaceOnUse"><circle cx="50" cy="50" r="1" fill="white" opacity="0.1"/></pattern></defs><rect width="100" height="100" fill="url(%23grain)"/></svg>');
          opacity: 0.3;
        }

        .tool-header {
          display: flex;
          align-items: center;
          gap: 1rem;
          margin-bottom: 2rem;
          position: relative;
          z-index: 1;
        }

        .tool-icon {
          font-size: 2.5rem;
          opacity: 0.9;
        }

        .tool-title-section {
          flex: 1;
        }

        .tool-title {
          font-size: 2rem;
          font-weight: 700;
          margin: 0;
          text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }

        .tool-subtitle {
          font-size: 1.1rem;
          margin: 0.5rem 0 0 0;
          opacity: 0.9;
          font-weight: 300;
        }

        .input-section {
          position: relative;
          z-index: 1;
          margin-bottom: 2rem;
        }

        .input-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
        }

        .input-label {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-weight: 600;
          font-size: 1rem;
        }

        .label-icon {
          opacity: 0.8;
        }

        .text-stats {
          display: flex;
          gap: 1rem;
        }

        .stat-item {
          display: flex;
          align-items: center;
          gap: 0.25rem;
          font-size: 0.9rem;
          opacity: 0.8;
        }

        .text-input {
          width: 100%;
          padding: 1rem;
          border: 2px solid rgba(255,255,255,0.2);
          border-radius: 12px;
          background: rgba(255,255,255,0.1);
          color: white;
          font-size: 1rem;
          line-height: 1.6;
          resize: vertical;
          min-height: 200px;
          backdrop-filter: blur(10px);
          transition: all 0.3s ease;
        }

        .text-input:focus {
          outline: none;
          border-color: rgba(255,255,255,0.5);
          background: rgba(255,255,255,0.15);
        }

        .text-input::placeholder {
          color: rgba(255,255,255,0.7);
        }

        .input-footer {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-top: 1rem;
          flex-wrap: wrap;
          gap: 1rem;
        }

        .summary-options {
          display: flex;
          align-items: center;
          gap: 0.75rem;
        }

        .option-label {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-weight: 600;
          font-size: 0.9rem;
        }

        .length-select {
          padding: 0.5rem 1rem;
          border: 2px solid rgba(255,255,255,0.3);
          border-radius: 8px;
          background: rgba(255,255,255,0.1);
          color: white;
          font-size: 0.9rem;
          cursor: pointer;
          backdrop-filter: blur(10px);
        }

        .length-select:focus {
          outline: none;
          border-color: rgba(255,255,255,0.5);
        }

        .length-select option {
          background: #667eea;
          color: white;
        }

        .requirements {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-size: 0.9rem;
          opacity: 0.8;
        }

        .btn-primary {
          background: linear-gradient(45deg, #ff6b6b, #ee5a24);
          border: none;
          border-radius: 12px;
          padding: 1rem 2rem;
          color: white;
          font-weight: 600;
          font-size: 1rem;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          transition: all 0.3s ease;
          box-shadow: 0 4px 15px rgba(255,107,107,0.4);
        }

        .btn-primary:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 6px 20px rgba(255,107,107,0.6);
        }

        .btn-primary:disabled {
          opacity: 0.6;
          cursor: not-allowed;
          transform: none;
        }

        .btn-secondary {
          background: rgba(255,255,255,0.2);
          border: 2px solid rgba(255,255,255,0.3);
          border-radius: 12px;
          padding: 0.75rem 1.5rem;
          color: white;
          font-weight: 600;
          font-size: 0.9rem;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          transition: all 0.3s ease;
          backdrop-filter: blur(10px);
        }

        .btn-secondary:hover {
          background: rgba(255,255,255,0.3);
          border-color: rgba(255,255,255,0.5);
        }

        .results-section {
          margin-top: 2rem;
          position: relative;
          z-index: 1;
        }

        .results-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
        }

        .results-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          font-size: 1.25rem;
          font-weight: 600;
        }

        .title-icon {
          opacity: 0.8;
        }

        .results-actions {
          display: flex;
          gap: 0.75rem;
        }

        .summary-stats {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 1.5rem;
          margin-bottom: 2rem;
        }

        .stat-card {
          background: rgba(255,255,255,0.1);
          border-radius: 16px;
          padding: 1.5rem;
          text-align: center;
          backdrop-filter: blur(10px);
          border: 2px solid rgba(255,255,255,0.2);
        }

        .stat-icon {
          font-size: 2rem;
          margin-bottom: 1rem;
        }

        .stat-value {
          font-size: 2.5rem;
          font-weight: 700;
          margin-bottom: 0.5rem;
        }

        .stat-label {
          font-size: 1rem;
          font-weight: 500;
          margin-bottom: 0.5rem;
        }

        .stat-status {
          font-size: 0.9rem;
          font-weight: 600;
        }

        .stat-subtitle {
          font-size: 0.8rem;
          opacity: 0.8;
        }

        .summary-text-section, .key-points-section, .detailed-stats-section {
          margin-bottom: 2rem;
        }

        .summary-text-title, .key-points-title, .detailed-stats-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          font-size: 1.1rem;
          font-weight: 600;
          margin-bottom: 1rem;
        }

        .summary-text-content {
          background: rgba(255,255,255,0.1);
          border-radius: 12px;
          padding: 1.5rem;
          backdrop-filter: blur(10px);
          line-height: 1.7;
          font-size: 1.1rem;
        }

        .key-points-list {
          display: flex;
          flex-direction: column;
          gap: 0.75rem;
        }

        .key-point-item {
          display: flex;
          align-items: center;
          gap: 1rem;
          background: rgba(255,255,255,0.1);
          border-radius: 8px;
          padding: 1rem;
          backdrop-filter: blur(10px);
        }

        .key-point-number {
          background: linear-gradient(45deg, #4ecdc4, #44a08d);
          color: white;
          width: 24px;
          height: 24px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 600;
          font-size: 0.8rem;
          flex-shrink: 0;
        }

        .key-point-text {
          color: rgba(255,255,255,0.9);
        }

        .detailed-stats-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
          gap: 1rem;
        }

        .detailed-stat-card {
          background: rgba(255,255,255,0.1);
          border-radius: 12px;
          padding: 1rem;
          text-align: center;
          backdrop-filter: blur(10px);
        }

        .detailed-stat-icon {
          font-size: 1.5rem;
          margin-bottom: 0.75rem;
          opacity: 0.8;
        }

        .detailed-stat-value {
          font-size: 1.5rem;
          font-weight: 700;
          margin-bottom: 0.25rem;
        }

        .detailed-stat-label {
          font-size: 0.8rem;
          opacity: 0.8;
        }

        .info-card, .how-to-card, .features-card, .use-cases-card {
          background: var(--bg-card);
          border: 1px solid var(--border);
          border-radius: 16px;
          padding: 2rem;
          box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }

        .info-title, .how-to-title, .features-title, .use-cases-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          margin-bottom: 1.5rem;
          color: var(--text-primary);
          font-size: 1.25rem;
          font-weight: 600;
        }

        .title-icon {
          color: var(--accent);
        }

        .info-content {
          color: var(--text-secondary);
          line-height: 1.7;
        }

        .info-content p {
          margin-bottom: 1rem;
        }

        .steps-list {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .step {
          display: flex;
          gap: 1rem;
          align-items: flex-start;
        }

        .step-number {
          background: linear-gradient(45deg, var(--accent), #667eea);
          color: white;
          width: 32px;
          height: 32px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 600;
          font-size: 0.9rem;
          flex-shrink: 0;
        }

        .step-content h4 {
          margin: 0 0 0.5rem 0;
          color: var(--text-primary);
          font-size: 1rem;
        }

        .step-content p {
          margin: 0;
          color: var(--text-secondary);
          line-height: 1.6;
        }

        .features-grid, .use-cases-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 1.5rem;
        }

        .feature, .use-case {
          text-align: center;
          padding: 1.5rem;
          border-radius: 12px;
          background: var(--bg-secondary);
          border: 1px solid var(--border);
          transition: all 0.3s ease;
        }

        .feature:hover, .use-case:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 25px rgba(0,0,0,0.1);
        }

        .feature-icon, .use-case-icon {
          font-size: 2rem;
          color: var(--accent);
          margin-bottom: 1rem;
        }

        .feature h4, .use-case h4 {
          margin: 0 0 0.75rem 0;
          color: var(--text-primary);
          font-size: 1rem;
        }

        .feature p, .use-case p {
          margin: 0;
          color: var(--text-secondary);
          font-size: 0.9rem;
          line-height: 1.5;
        }

        @media (max-width: 768px) {
          .tool-container {
            padding: 1rem;
          }
          
          .input-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }
          
          .input-footer {
            flex-direction: column;
            align-items: stretch;
            gap: 1rem;
          }
          
          .summary-options {
            justify-content: center;
          }
          
          .results-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }
          
          .results-actions {
            flex-wrap: wrap;
          }
          
          .summary-stats {
            grid-template-columns: 1fr;
          }
          
          .detailed-stats-grid {
            grid-template-columns: repeat(2, 1fr);
          }
        }
      `}</style>
    </div>
  )
}

export default TextSummarizer

