import { useState, useCallback } from 'react'
import FontAwesomeIcon from '../../components/FontAwesomeIcon'

const GrammarChecker = () => {
  const [text, setText] = useState('')
  const [isChecking, setIsChecking] = useState(false)
  const [results, setResults] = useState(null)
  const [wordCount, setWordCount] = useState(0)
  const [charCount, setCharCount] = useState(0)

  const handleTextChange = useCallback((e) => {
    const value = e.target.value
    setText(value)
    setWordCount(value.trim() ? value.trim().split(/\s+/).length : 0)
    setCharCount(value.length)
  }, [])

  const checkGrammar = useCallback(async () => {
    if (!text.trim()) {
      alert('Please enter some text to check')
      return
    }

    if (text.length < 10) {
      alert('Please enter at least 10 characters for grammar checking')
      return
    }

    setIsChecking(true)
    
    // Simulate API call with realistic delay
    setTimeout(() => {
      // Simulate grammar checking results
      const simulatedResults = {
        score: Math.floor(Math.random() * 30) + 70, // 70-100
        errors: [
          {
            type: 'grammar',
            message: 'Consider using "its" instead of "it\'s" in this context',
            suggestion: 'its',
            position: { start: 45, end: 50 },
            severity: 'medium'
          },
          {
            type: 'spelling',
            message: 'Possible spelling error: "recieve" should be "receive"',
            suggestion: 'receive',
            position: { start: 120, end: 128 },
            severity: 'high'
          },
          {
            type: 'style',
            message: 'Consider using a more concise phrase',
            suggestion: 'Use "because" instead of "due to the fact that"',
            position: { start: 200, end: 225 },
            severity: 'low'
          }
        ],
        suggestions: [
          'Use active voice instead of passive voice',
          'Consider shorter sentences for better readability',
          'Add transitional words to improve flow',
          'Check for consistent tense usage'
        ],
        stats: {
          readabilityScore: Math.floor(Math.random() * 20) + 60, // 60-80
          avgWordsPerSentence: Math.floor(Math.random() * 5) + 12, // 12-17
          passiveVoiceCount: Math.floor(Math.random() * 3),
          complexWordsCount: Math.floor(Math.random() * 5) + 2
        },
        checkedAt: new Date().toISOString()
      }
      
      setResults(simulatedResults)
      setIsChecking(false)
    }, 1500)
  }, [text])

  const applySuggestion = (errorIndex) => {
    if (!results || !results.errors[errorIndex]) return
    
    const error = results.errors[errorIndex]
    const beforeText = text.substring(0, error.position.start)
    const afterText = text.substring(error.position.end)
    const newText = beforeText + error.suggestion + afterText
    
    setText(newText)
    
    // Remove the error from results
    const updatedResults = {
      ...results,
      errors: results.errors.filter((_, index) => index !== errorIndex)
    }
    setResults(updatedResults)
  }

  const copyResults = async () => {
    if (results) {
      const report = `Grammar Check Report:
Score: ${results.score}/100
Errors Found: ${results.errors.length}
Readability Score: ${results.stats.readabilityScore}/100
Average Words per Sentence: ${results.stats.avgWordsPerSentence}

Errors:
${results.errors.map((error, index) => `${index + 1}. ${error.message} (${error.severity})`).join('\n')}

Suggestions:
${results.suggestions.map((suggestion, index) => `${index + 1}. ${suggestion}`).join('\n')}

Checked on: ${new Date(results.checkedAt).toLocaleString()}`
      
      try {
        await navigator.clipboard.writeText(report)
      } catch (err) {
        console.error('Failed to copy: ', err)
      }
    }
  }

  const downloadReport = () => {
    if (!results) return
    
    const report = `GRAMMAR CHECK REPORT
Generated: ${new Date(results.checkedAt).toLocaleString()}

TEXT ANALYSIS:
Word Count: ${wordCount}
Character Count: ${charCount}

GRAMMAR SCORE: ${results.score}/100
Readability Score: ${results.stats.readabilityScore}/100
Average Words per Sentence: ${results.stats.avgWordsPerSentence}
Passive Voice Count: ${results.stats.passiveVoiceCount}
Complex Words Count: ${results.stats.complexWordsCount}

ERRORS FOUND (${results.errors.length}):
${results.errors.map((error, index) => `
${index + 1}. ${error.type.toUpperCase()} - ${error.severity.toUpperCase()}
   Message: ${error.message}
   Suggestion: ${error.suggestion}
   Position: ${error.position.start}-${error.position.end}
`).join('')}

IMPROVEMENT SUGGESTIONS:
${results.suggestions.map((suggestion, index) => `${index + 1}. ${suggestion}`).join('\n')}

---
Report generated by TrimToolsHub Grammar Checker
https://www.trimtoolshub.com/tools/grammar-checker`
    
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `grammar-report-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const clearResults = () => {
    setResults(null)
  }

  const getScoreColor = (score) => {
    if (score >= 90) return '#10b981' // Green
    if (score >= 70) return '#f59e0b' // Yellow
    return '#ef4444' // Red
  }

  const getScoreStatus = (score) => {
    if (score >= 90) return 'Excellent'
    if (score >= 70) return 'Good'
    if (score >= 50) return 'Fair'
    return 'Needs Improvement'
  }

  const getSeverityColor = (severity) => {
    switch (severity) {
      case 'high': return '#ef4444'
      case 'medium': return '#f59e0b'
      case 'low': return '#10b981'
      default: return '#6b7280'
    }
  }

  const getSeverityIcon = (severity) => {
    switch (severity) {
      case 'high': return 'fas fa-exclamation-circle'
      case 'medium': return 'fas fa-exclamation-triangle'
      case 'low': return 'fas fa-info-circle'
      default: return 'fas fa-question-circle'
    }
  }

  return (
    <div className="tool-container">
      {/* Main Tool Interface */}
      <div className="tool-card">
        <h2 style={{ marginBottom: '1.5rem', color: 'var(--text-primary)' }}>
          <FontAwesomeIcon icon="fas fa-spell-check" style={{ marginRight: '0.5rem', color: 'var(--accent)' }} />
          Grammar Checker
        </h2>
        
        <div style={{ 
          backgroundColor: 'var(--bg-secondary)', 
          border: '1px solid var(--border)', 
          borderRadius: '0.75rem', 
          padding: '1.5rem',
          marginBottom: '2rem',
          color: 'var(--text-secondary)',
          lineHeight: '1.6'
        }}>
          <p style={{ marginBottom: '1rem', fontSize: '1.1rem' }}>
            Improve your writing with our comprehensive Grammar Checker that detects grammar errors, 
            spelling mistakes, and style issues. Whether you're writing academic papers, professional 
            documents, or casual content, our tool provides detailed feedback with actionable suggestions 
            to enhance your writing quality and readability.
          </p>
          
          <p style={{ marginBottom: '1rem' }}>
            Our Grammar Checker analyzes your text for common grammar mistakes, spelling errors, 
            punctuation issues, and style problems. It provides readability scores, text statistics, 
            and improvement suggestions to help you write more effectively and professionally. 
            All processing happens securely in your browser without storing your content.
          </p>
          
          <p style={{ marginBottom: '1rem' }}>
            Perfect for students, professionals, content creators, and anyone who wants to improve 
            their writing skills. The tool helps you catch errors before publishing, improve readability, 
            and learn from detailed explanations and suggestions for better writing practices.
          </p>
          
          <p style={{ margin: 0 }}>
            Features include real-time error detection, one-click fixes, readability analysis, 
            detailed statistics, export capabilities, and comprehensive documentation about 
            grammar rules and writing best practices.
          </p>
        </div>

        {/* Text Input Section */}
        <div className="input-section">
          <div className="input-header">
            <label className="input-label">
              <FontAwesomeIcon icon="fas fa-edit" className="label-icon" />
              Enter Text to Check
            </label>
            <div className="text-stats">
              <span className="stat-item">
                <FontAwesomeIcon icon="fas fa-font" />
                {wordCount} words
              </span>
              <span className="stat-item">
                <FontAwesomeIcon icon="fas fa-keyboard" />
                {charCount} characters
              </span>
            </div>
          </div>
          
          <textarea
            value={text}
            onChange={handleTextChange}
            placeholder="Paste your text here to check for grammar, spelling, and style issues..."
            className="text-input"
            rows={8}
          />
          
          <div className="input-footer">
            <div className="requirements">
              <FontAwesomeIcon icon="fas fa-info-circle" />
              <span>Minimum 10 characters required • Supports up to 10,000 characters</span>
            </div>
            <button
              onClick={checkGrammar}
              disabled={isChecking || text.length < 10}
              className="btn-primary"
            >
              <FontAwesomeIcon icon={isChecking ? "fas fa-spinner fa-spin" : "fas fa-spell-check"} />
              {isChecking ? 'Checking...' : 'Check Grammar'}
            </button>
          </div>
        </div>

        {/* Results Section */}
        {results && (
          <div className="results-section">
            <div className="results-header">
              <h3 className="results-title">
                <FontAwesomeIcon icon="fas fa-chart-line" className="title-icon" />
                Grammar Check Results
              </h3>
              <div className="results-actions">
                <button onClick={copyResults} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-copy" />
                  Copy Report
                </button>
                <button onClick={downloadReport} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-download" />
                  Download
                </button>
                <button onClick={clearResults} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-trash" />
                  Clear
                </button>
              </div>
            </div>

            {/* Main Results */}
            <div className="grammar-summary">
              <div className="summary-card score" style={{ borderColor: getScoreColor(results.score) }}>
                <div className="summary-icon" style={{ color: getScoreColor(results.score) }}>
                  <FontAwesomeIcon icon="fas fa-star" />
                </div>
                <div className="summary-content">
                  <div className="summary-percentage" style={{ color: getScoreColor(results.score) }}>
                    {results.score}/100
                  </div>
                  <div className="summary-label">Grammar Score</div>
                  <div className="summary-status" style={{ color: getScoreColor(results.score) }}>
                    {getScoreStatus(results.score)}
                  </div>
                </div>
              </div>
              
              <div className="summary-card errors">
                <div className="summary-icon" style={{ color: results.errors.length > 0 ? '#ef4444' : '#10b981' }}>
                  <FontAwesomeIcon icon={results.errors.length > 0 ? "fas fa-exclamation-triangle" : "fas fa-check-circle"} />
                </div>
                <div className="summary-content">
                  <div className="summary-percentage" style={{ color: results.errors.length > 0 ? '#ef4444' : '#10b981' }}>
                    {results.errors.length}
                  </div>
                  <div className="summary-label">Issues Found</div>
                </div>
              </div>

              <div className="summary-card readability">
                <div className="summary-icon" style={{ color: getScoreColor(results.stats.readabilityScore) }}>
                  <FontAwesomeIcon icon="fas fa-book-reader" />
                </div>
                <div className="summary-content">
                  <div className="summary-percentage" style={{ color: getScoreColor(results.stats.readabilityScore) }}>
                    {results.stats.readabilityScore}/100
                  </div>
                  <div className="summary-label">Readability</div>
                </div>
              </div>
            </div>

            {/* Errors Found */}
            {results.errors.length > 0 && (
              <div className="errors-section">
                <h4 className="errors-title">
                  <FontAwesomeIcon icon="fas fa-exclamation-triangle" className="title-icon" />
                  Issues Found ({results.errors.length})
                </h4>
                <div className="errors-list">
                  {results.errors.map((error, index) => (
                    <div key={index} className="error-item">
                      <div className="error-header">
                        <div className="error-type">
                          <FontAwesomeIcon 
                            icon={getSeverityIcon(error.severity)} 
                            style={{ color: getSeverityColor(error.severity) }}
                          />
                          <span className="error-type-text">{error.type}</span>
                          <span className="error-severity" style={{ color: getSeverityColor(error.severity) }}>
                            {error.severity}
                          </span>
                        </div>
                        <button 
                          onClick={() => applySuggestion(index)}
                          className="apply-suggestion-btn"
                        >
                          <FontAwesomeIcon icon="fas fa-check" />
                          Apply Fix
                        </button>
                      </div>
                      <p className="error-message">{error.message}</p>
                      <div className="error-suggestion">
                        <strong>Suggestion:</strong> {error.suggestion}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Statistics */}
            <div className="stats-section">
              <h4 className="stats-title">
                <FontAwesomeIcon icon="fas fa-chart-bar" className="title-icon" />
                Text Statistics
              </h4>
              <div className="stats-grid">
                <div className="stat-card">
                  <div className="stat-icon">
                    <FontAwesomeIcon icon="fas fa-sentence" />
                  </div>
                  <div className="stat-content">
                    <div className="stat-value">{results.stats.avgWordsPerSentence}</div>
                    <div className="stat-label">Avg Words/Sentence</div>
                  </div>
                </div>
                <div className="stat-card">
                  <div className="stat-icon">
                    <FontAwesomeIcon icon="fas fa-eye-slash" />
                  </div>
                  <div className="stat-content">
                    <div className="stat-value">{results.stats.passiveVoiceCount}</div>
                    <div className="stat-label">Passive Voice</div>
                  </div>
                </div>
                <div className="stat-card">
                  <div className="stat-icon">
                    <FontAwesomeIcon icon="fas fa-brain" />
                  </div>
                  <div className="stat-content">
                    <div className="stat-value">{results.stats.complexWordsCount}</div>
                    <div className="stat-label">Complex Words</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Suggestions */}
            <div className="suggestions-section">
              <h4 className="suggestions-title">
                <FontAwesomeIcon icon="fas fa-lightbulb" className="title-icon" />
                Improvement Suggestions
              </h4>
              <div className="suggestions-list">
                {results.suggestions.map((suggestion, index) => (
                  <div key={index} className="suggestion-item">
                    <FontAwesomeIcon icon="fas fa-arrow-right" className="suggestion-icon" />
                    <span className="suggestion-text">{suggestion}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Tool Information */}
      <div style={{ 
        backgroundColor: 'var(--bg-card)', 
        border: '1px solid var(--border)', 
        borderRadius: '1rem', 
        padding: '2rem',
        marginTop: '2rem'
      }}>
        <h3 style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>
          <FontAwesomeIcon icon="fas fa-info-circle" style={{ marginRight: '0.5rem', color: 'var(--accent)' }} />
          About Grammar Checking
        </h3>
        
        <div style={{ color: 'var(--text-secondary)', lineHeight: '1.6' }}>
          <h4 style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>Frequently Asked Questions</h4>
          
          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What types of errors does the Grammar Checker detect?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our Grammar Checker identifies grammar errors (subject-verb agreement, tense consistency, 
              sentence structure), spelling mistakes (typos, incorrect words), punctuation issues 
              (missing commas, incorrect apostrophes), and style problems (wordiness, passive voice, 
              readability issues). It also provides suggestions for improving clarity and conciseness.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How accurate is the grammar checking?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our Grammar Checker uses advanced language processing algorithms to provide high accuracy 
              in error detection. However, like all automated tools, it may occasionally miss subtle 
              errors or suggest changes that aren't necessary. We recommend using it as a helpful 
              writing assistant rather than a replacement for human proofreading, especially for 
              important documents.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Is my text stored or shared when using this tool?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              No, your text is processed entirely in your browser and is never sent to our servers 
              or stored anywhere. All grammar checking happens locally on your device, ensuring 
              complete privacy and security for your content. This makes it safe to use with 
              sensitive or confidential documents.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What is a readability score and how is it calculated?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              The readability score measures how easy your text is to understand. It considers factors 
              like sentence length, word complexity, and vocabulary difficulty. Higher scores (80-100) 
              indicate easier reading, while lower scores suggest more complex text. The score helps 
              you adjust your writing style for your target audience.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How do I improve my grammar score?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              To improve your grammar score: fix all detected errors, use active voice instead of passive, 
              keep sentences concise and clear, ensure proper punctuation, maintain consistent tense, 
              and avoid complex sentence structures. The tool provides specific suggestions for each 
              detected issue to help you improve systematically.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Can I use this tool for different types of writing?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Yes, the Grammar Checker works for various writing types including academic papers, 
              business documents, blog posts, emails, and creative writing. However, keep in mind 
              that different writing styles have different conventions. For example, academic writing 
              may use more complex sentences, while business writing should be more concise.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What's the difference between grammar and style suggestions?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Grammar suggestions fix actual errors that make text incorrect (like "their" vs "there"). 
              Style suggestions improve clarity, conciseness, and readability without fixing errors 
              (like suggesting shorter sentences or active voice). Both are important for professional 
              writing, but grammar fixes are essential while style improvements are recommendations.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How can I learn from the grammar checker's suggestions?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Pay attention to the explanations provided with each suggestion. Look for patterns in 
              the errors you make most frequently. Use the tool regularly to identify your common 
              mistakes and focus on improving those areas. The detailed feedback helps you understand 
              grammar rules and develop better writing habits over time.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Should I accept all suggestions automatically?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              No, always review suggestions before applying them. While grammar fixes are usually correct, 
              style suggestions are subjective and depend on your writing context and audience. Consider 
              whether each suggestion improves your specific text and maintains your intended tone and 
              voice. Use your judgment to decide which suggestions to accept.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Can this tool help with non-English text?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Currently, our Grammar Checker is optimized for English text. It may not provide accurate 
              suggestions for other languages. For non-English content, we recommend using language-specific 
              grammar checking tools or consulting native speakers for proper grammar and style guidance.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What are the best practices for using a grammar checker?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Best practices include: checking your text after writing but before finalizing, reading 
              suggestions carefully before applying them, using the tool as a learning opportunity, 
              not relying solely on automated checking for important documents, and combining the tool 
              with manual proofreading for best results.
            </p>
          </div>
        </div>
      </div>

      {/* How to Use */}
      <div className="how-to-card">
        <h3 className="how-to-title">
          <FontAwesomeIcon icon="fas fa-play-circle" className="title-icon" />
          How to Use Grammar Checker
        </h3>
        <div className="steps-list">
          <div className="step">
            <div className="step-number">1</div>
            <div className="step-content">
              <h4>Enter Your Text</h4>
              <p>Paste or type your text into the input field. Minimum 10 characters required for checking.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">2</div>
            <div className="step-content">
              <h4>Start the Check</h4>
              <p>Click "Check Grammar" to begin the analysis. The process typically takes 1-2 seconds.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">3</div>
            <div className="step-content">
              <h4>Review & Apply</h4>
              <p>Examine the grammar score, errors found, and suggestions. Apply fixes directly to your text.</p>
            </div>
          </div>
        </div>
      </div>

      {/* Features */}
      <div className="features-card">
        <h3 className="features-title">
          <FontAwesomeIcon icon="fas fa-star" className="title-icon" />
          Key Features
        </h3>
        <div className="features-grid">
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-shield-alt" className="feature-icon" />
            <h4>Privacy Protected</h4>
            <p>Your text is processed securely and never stored on our servers</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-search" className="feature-icon" />
            <h4>Comprehensive Check</h4>
            <p>Detects grammar, spelling, punctuation, and style issues</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-chart-line" className="feature-icon" />
            <h4>Readability Analysis</h4>
            <p>Provides readability scores and text statistics</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-magic" className="feature-icon" />
            <h4>One-Click Fixes</h4>
            <p>Apply suggested corrections directly to your text</p>
          </div>
        </div>
      </div>

      {/* Use Cases */}
      <div className="use-cases-card">
        <h3 className="use-cases-title">
          <FontAwesomeIcon icon="fas fa-lightbulb" className="title-icon" />
          Popular Use Cases
        </h3>
        <div className="use-cases-grid">
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-graduation-cap" className="use-case-icon" />
            <h4>Academic Writing</h4>
            <p>Check essays, research papers, and assignments for errors</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-briefcase" className="use-case-icon" />
            <h4>Professional Documents</h4>
            <p>Ensure reports, emails, and proposals are error-free</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-blog" className="use-case-icon" />
            <h4>Content Creation</h4>
            <p>Improve blog posts, articles, and web content quality</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-envelope" className="use-case-icon" />
            <h4>Communication</h4>
            <p>Polish emails, messages, and social media posts</p>
          </div>
        </div>
      </div>

      <style jsx>{`
        .tool-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 2rem;
          display: flex;
          flex-direction: column;
          gap: 2rem;
        }

        .tool-card {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          border-radius: 24px;
          padding: 2rem;
          color: white;
          box-shadow: 0 20px 40px rgba(0,0,0,0.1);
          position: relative;
          overflow: hidden;
        }

        .tool-card::before {
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><pattern id="grain" width="100" height="100" patternUnits="userSpaceOnUse"><circle cx="50" cy="50" r="1" fill="white" opacity="0.1"/></pattern></defs><rect width="100" height="100" fill="url(%23grain)"/></svg>');
          opacity: 0.3;
        }

        .tool-header {
          display: flex;
          align-items: center;
          gap: 1rem;
          margin-bottom: 2rem;
          position: relative;
          z-index: 1;
        }

        .tool-icon {
          font-size: 2.5rem;
          opacity: 0.9;
        }

        .tool-title-section {
          flex: 1;
        }

        .tool-title {
          font-size: 2rem;
          font-weight: 700;
          margin: 0;
          text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }

        .tool-subtitle {
          font-size: 1.1rem;
          margin: 0.5rem 0 0 0;
          opacity: 0.9;
          font-weight: 300;
        }

        .input-section {
          position: relative;
          z-index: 1;
          margin-bottom: 2rem;
        }

        .input-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
        }

        .input-label {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-weight: 600;
          font-size: 1rem;
        }

        .label-icon {
          opacity: 0.8;
        }

        .text-stats {
          display: flex;
          gap: 1rem;
        }

        .stat-item {
          display: flex;
          align-items: center;
          gap: 0.25rem;
          font-size: 0.9rem;
          opacity: 0.8;
        }

        .text-input {
          width: 100%;
          padding: 1rem;
          border: 2px solid rgba(255,255,255,0.2);
          border-radius: 12px;
          background: rgba(255,255,255,0.1);
          color: white;
          font-size: 1rem;
          line-height: 1.6;
          resize: vertical;
          min-height: 200px;
          backdrop-filter: blur(10px);
          transition: all 0.3s ease;
        }

        .text-input:focus {
          outline: none;
          border-color: rgba(255,255,255,0.5);
          background: rgba(255,255,255,0.15);
        }

        .text-input::placeholder {
          color: rgba(255,255,255,0.7);
        }

        .input-footer {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-top: 1rem;
        }

        .requirements {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-size: 0.9rem;
          opacity: 0.8;
        }

        .btn-primary {
          background: linear-gradient(45deg, #ff6b6b, #ee5a24);
          border: none;
          border-radius: 12px;
          padding: 1rem 2rem;
          color: white;
          font-weight: 600;
          font-size: 1rem;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          transition: all 0.3s ease;
          box-shadow: 0 4px 15px rgba(255,107,107,0.4);
        }

        .btn-primary:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 6px 20px rgba(255,107,107,0.6);
        }

        .btn-primary:disabled {
          opacity: 0.6;
          cursor: not-allowed;
          transform: none;
        }

        .btn-secondary {
          background: rgba(255,255,255,0.2);
          border: 2px solid rgba(255,255,255,0.3);
          border-radius: 12px;
          padding: 0.75rem 1.5rem;
          color: white;
          font-weight: 600;
          font-size: 0.9rem;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          transition: all 0.3s ease;
          backdrop-filter: blur(10px);
        }

        .btn-secondary:hover {
          background: rgba(255,255,255,0.3);
          border-color: rgba(255,255,255,0.5);
        }

        .apply-suggestion-btn {
          background: linear-gradient(45deg, #10b981, #059669);
          border: none;
          border-radius: 8px;
          padding: 0.5rem 1rem;
          color: white;
          font-weight: 500;
          font-size: 0.8rem;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.25rem;
          transition: all 0.3s ease;
        }

        .apply-suggestion-btn:hover {
          transform: translateY(-1px);
          box-shadow: 0 4px 12px rgba(16, 185, 129, 0.4);
        }

        .results-section {
          margin-top: 2rem;
          position: relative;
          z-index: 1;
        }

        .results-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
        }

        .results-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          font-size: 1.25rem;
          font-weight: 600;
        }

        .title-icon {
          opacity: 0.8;
        }

        .results-actions {
          display: flex;
          gap: 0.75rem;
        }

        .grammar-summary {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 1.5rem;
          margin-bottom: 2rem;
        }

        .summary-card {
          background: rgba(255,255,255,0.1);
          border-radius: 16px;
          padding: 1.5rem;
          text-align: center;
          backdrop-filter: blur(10px);
          border: 2px solid rgba(255,255,255,0.2);
        }

        .summary-icon {
          font-size: 2rem;
          margin-bottom: 1rem;
        }

        .summary-percentage {
          font-size: 2.5rem;
          font-weight: 700;
          margin-bottom: 0.5rem;
        }

        .summary-label {
          font-size: 1rem;
          font-weight: 500;
          margin-bottom: 0.5rem;
        }

        .summary-status {
          font-size: 0.9rem;
          font-weight: 600;
        }

        .errors-section, .stats-section, .suggestions-section {
          margin-bottom: 2rem;
        }

        .errors-title, .stats-title, .suggestions-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          font-size: 1.1rem;
          font-weight: 600;
          margin-bottom: 1rem;
        }

        .errors-list {
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        .error-item {
          background: rgba(255,255,255,0.1);
          border-radius: 12px;
          padding: 1.5rem;
          backdrop-filter: blur(10px);
        }

        .error-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
        }

        .error-type {
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }

        .error-type-text {
          font-weight: 600;
          text-transform: capitalize;
        }

        .error-severity {
          font-size: 0.8rem;
          font-weight: 600;
          text-transform: uppercase;
        }

        .error-message {
          color: rgba(255,255,255,0.9);
          line-height: 1.6;
          margin-bottom: 0.75rem;
        }

        .error-suggestion {
          color: rgba(255,255,255,0.8);
          font-size: 0.9rem;
        }

        .stats-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
          gap: 1rem;
        }

        .stat-card {
          background: rgba(255,255,255,0.1);
          border-radius: 12px;
          padding: 1rem;
          text-align: center;
          backdrop-filter: blur(10px);
        }

        .stat-icon {
          font-size: 1.5rem;
          margin-bottom: 0.75rem;
          opacity: 0.8;
        }

        .stat-value {
          font-size: 1.5rem;
          font-weight: 700;
          margin-bottom: 0.25rem;
        }

        .stat-label {
          font-size: 0.8rem;
          opacity: 0.8;
        }

        .suggestions-list {
          display: flex;
          flex-direction: column;
          gap: 0.75rem;
        }

        .suggestion-item {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          background: rgba(255,255,255,0.1);
          border-radius: 8px;
          padding: 1rem;
          backdrop-filter: blur(10px);
        }

        .suggestion-icon {
          color: #feca57;
          font-size: 0.9rem;
        }

        .suggestion-text {
          color: rgba(255,255,255,0.9);
        }

        .info-card, .how-to-card, .features-card, .use-cases-card {
          background: var(--bg-card);
          border: 1px solid var(--border);
          border-radius: 16px;
          padding: 2rem;
          box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }

        .info-title, .how-to-title, .features-title, .use-cases-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          margin-bottom: 1.5rem;
          color: var(--text-primary);
          font-size: 1.25rem;
          font-weight: 600;
        }

        .title-icon {
          color: var(--accent);
        }

        .info-content {
          color: var(--text-secondary);
          line-height: 1.7;
        }

        .info-content p {
          margin-bottom: 1rem;
        }

        .steps-list {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .step {
          display: flex;
          gap: 1rem;
          align-items: flex-start;
        }

        .step-number {
          background: linear-gradient(45deg, var(--accent), #667eea);
          color: white;
          width: 32px;
          height: 32px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 600;
          font-size: 0.9rem;
          flex-shrink: 0;
        }

        .step-content h4 {
          margin: 0 0 0.5rem 0;
          color: var(--text-primary);
          font-size: 1rem;
        }

        .step-content p {
          margin: 0;
          color: var(--text-secondary);
          line-height: 1.6;
        }

        .features-grid, .use-cases-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 1.5rem;
        }

        .feature, .use-case {
          text-align: center;
          padding: 1.5rem;
          border-radius: 12px;
          background: var(--bg-secondary);
          border: 1px solid var(--border);
          transition: all 0.3s ease;
        }

        .feature:hover, .use-case:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 25px rgba(0,0,0,0.1);
        }

        .feature-icon, .use-case-icon {
          font-size: 2rem;
          color: var(--accent);
          margin-bottom: 1rem;
        }

        .feature h4, .use-case h4 {
          margin: 0 0 0.75rem 0;
          color: var(--text-primary);
          font-size: 1rem;
        }

        .feature p, .use-case p {
          margin: 0;
          color: var(--text-secondary);
          font-size: 0.9rem;
          line-height: 1.5;
        }

        @media (max-width: 768px) {
          .tool-container {
            padding: 1rem;
          }
          
          .input-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }
          
          .results-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }
          
          .results-actions {
            flex-wrap: wrap;
          }
          
          .grammar-summary {
            grid-template-columns: 1fr;
          }
          
          .error-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 0.75rem;
          }
          
          .stats-grid {
            grid-template-columns: repeat(2, 1fr);
          }
        }
      `}</style>
    </div>
  )
}

export default GrammarChecker

