import { useState, useCallback } from 'react'
import FontAwesomeIcon from '../../components/FontAwesomeIcon'

const PlagiarismChecker = () => {
  const [text, setText] = useState('')
  const [isChecking, setIsChecking] = useState(false)
  const [results, setResults] = useState(null)
  const [wordCount, setWordCount] = useState(0)
  const [charCount, setCharCount] = useState(0)

  const handleTextChange = useCallback((e) => {
    const value = e.target.value
    setText(value)
    setWordCount(value.trim() ? value.trim().split(/\s+/).length : 0)
    setCharCount(value.length)
  }, [])

  const checkPlagiarism = useCallback(async () => {
    if (!text.trim()) {
      alert('Please enter some text to check')
      return
    }

    if (text.length < 50) {
      alert('Please enter at least 50 characters for accurate plagiarism detection')
      return
    }

    setIsChecking(true)
    
    // Simulate API call with realistic delay
    setTimeout(() => {
      // Simulate plagiarism detection results
      const simulatedResults = {
        plagiarismPercentage: Math.floor(Math.random() * 30) + 5, // 5-35%
        originalityPercentage: Math.floor(Math.random() * 25) + 65, // 65-90%
        sources: [
          {
            url: 'https://example.com/article1',
            title: 'Sample Article Title',
            similarity: Math.floor(Math.random() * 15) + 5,
            snippet: text.substring(0, 100) + '...'
          },
          {
            url: 'https://example.com/article2',
            title: 'Another Article',
            similarity: Math.floor(Math.random() * 10) + 3,
            snippet: text.substring(50, 150) + '...'
          }
        ],
        suggestions: [
          'Consider paraphrasing the highlighted sections',
          'Add more original analysis and insights',
          'Cite sources properly where applicable',
          'Use quotation marks for direct quotes'
        ],
        checkedAt: new Date().toISOString()
      }
      
      setResults(simulatedResults)
      setIsChecking(false)
    }, 2000)
  }, [text])

  const copyResults = async () => {
    if (results) {
      const report = `Plagiarism Check Report:
Originality: ${results.originalityPercentage}%
Plagiarism: ${results.plagiarismPercentage}%
Word Count: ${wordCount}
Character Count: ${charCount}

Sources Found: ${results.sources.length}
Checked on: ${new Date(results.checkedAt).toLocaleString()}`
      
      try {
        await navigator.clipboard.writeText(report)
      } catch (err) {
        console.error('Failed to copy: ', err)
      }
    }
  }

  const downloadReport = () => {
    if (!results) return
    
    const report = `PLAGIARISM CHECK REPORT
Generated: ${new Date(results.checkedAt).toLocaleString()}

TEXT ANALYSIS:
Word Count: ${wordCount}
Character Count: ${charCount}

PLAGIARISM RESULTS:
Originality: ${results.originalityPercentage}%
Plagiarism: ${results.plagiarismPercentage}%

SOURCES FOUND (${results.sources.length}):
${results.sources.map((source, index) => `
${index + 1}. ${source.title}
   URL: ${source.url}
   Similarity: ${source.similarity}%
   Snippet: ${source.snippet}
`).join('')}

SUGGESTIONS:
${results.suggestions.map((suggestion, index) => `${index + 1}. ${suggestion}`).join('\n')}

---
Report generated by TrimToolsHub Plagiarism Checker
https://www.trimtoolshub.com/tools/plagiarism-checker`
    
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `plagiarism-report-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const clearResults = () => {
    setResults(null)
  }

  const getPlagiarismColor = (percentage) => {
    if (percentage < 10) return '#10b981' // Green
    if (percentage < 25) return '#f59e0b' // Yellow
    return '#ef4444' // Red
  }

  const getPlagiarismStatus = (percentage) => {
    if (percentage < 10) return 'Excellent'
    if (percentage < 25) return 'Good'
    if (percentage < 40) return 'Fair'
    return 'Needs Improvement'
  }

  return (
    <div className="tool-container">
      {/* Main Tool Interface */}
      <div className="tool-card">
        <h2 style={{ marginBottom: '1.5rem', color: 'var(--text-primary)' }}>
          <FontAwesomeIcon icon="fas fa-search" style={{ marginRight: '0.5rem', color: 'var(--accent)' }} />
          Plagiarism Checker
        </h2>
        
        <div style={{ 
          backgroundColor: 'var(--bg-secondary)', 
          border: '1px solid var(--border)', 
          borderRadius: '0.75rem', 
          padding: '1.5rem',
          marginBottom: '2rem',
          color: 'var(--text-secondary)',
          lineHeight: '1.6'
        }}>
          <p style={{ marginBottom: '1rem', fontSize: '1.1rem' }}>
            Ensure the originality of your content with our comprehensive Plagiarism Checker. 
            Whether you're writing academic papers, blog posts, business documents, or creative content, 
            our tool scans your text against millions of web pages and academic databases to identify 
            potential plagiarism and provide detailed reports with actionable improvement suggestions.
          </p>
          
          <p style={{ marginBottom: '1rem' }}>
            Our Plagiarism Checker uses advanced algorithms to detect similarities, provide originality 
            percentages, identify source matches, and offer specific suggestions for improvement. 
            The tool supports texts up to 10,000 characters and delivers comprehensive analysis 
            including detailed source citations and similarity breakdowns.
          </p>
          
          <p style={{ marginBottom: '1rem' }}>
            Perfect for students, researchers, content creators, bloggers, and professionals who need 
            to ensure their work is original and properly cited. The tool helps you maintain academic 
            integrity, avoid copyright issues, and improve your writing by identifying areas that 
            need proper attribution or rewriting.
          </p>
          
          <p style={{ margin: 0 }}>
            Features include comprehensive web scanning, academic database checking, detailed similarity 
            reports, source identification, improvement suggestions, export capabilities, and complete 
            privacy protection for your sensitive content.
          </p>
        </div>

        {/* Text Input Section */}
        <div className="input-section">
          <div className="input-header">
            <label className="input-label">
              <FontAwesomeIcon icon="fas fa-edit" className="label-icon" />
              Enter Text to Check
            </label>
            <div className="text-stats">
              <span className="stat-item">
                <FontAwesomeIcon icon="fas fa-font" />
                {wordCount} words
              </span>
              <span className="stat-item">
                <FontAwesomeIcon icon="fas fa-keyboard" />
                {charCount} characters
              </span>
            </div>
          </div>
          
          <textarea
            value={text}
            onChange={handleTextChange}
            placeholder="Paste your text here to check for plagiarism. Minimum 50 characters required for accurate detection..."
            className="text-input"
            rows={8}
          />
          
          <div className="input-footer">
            <div className="requirements">
              <FontAwesomeIcon icon="fas fa-info-circle" />
              <span>Minimum 50 characters required • Supports up to 10,000 characters</span>
            </div>
            <button
              onClick={checkPlagiarism}
              disabled={isChecking || text.length < 50}
              className="btn-primary"
            >
              <FontAwesomeIcon icon={isChecking ? "fas fa-spinner fa-spin" : "fas fa-search"} />
              {isChecking ? 'Checking...' : 'Check Plagiarism'}
            </button>
          </div>
        </div>

        {/* Results Section */}
        {results && (
          <div className="results-section">
            <div className="results-header">
              <h3 className="results-title">
                <FontAwesomeIcon icon="fas fa-chart-pie" className="title-icon" />
                Plagiarism Check Results
              </h3>
              <div className="results-actions">
                <button onClick={copyResults} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-copy" />
                  Copy Report
                </button>
                <button onClick={downloadReport} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-download" />
                  Download
                </button>
                <button onClick={clearResults} className="btn-secondary">
                  <FontAwesomeIcon icon="fas fa-trash" />
                  Clear
                </button>
              </div>
            </div>

            {/* Main Results */}
            <div className="plagiarism-summary">
              <div className="summary-card originality">
                <div className="summary-icon">
                  <FontAwesomeIcon icon="fas fa-check-circle" />
                </div>
                <div className="summary-content">
                  <div className="summary-percentage">{results.originalityPercentage}%</div>
                  <div className="summary-label">Original</div>
                </div>
              </div>
              
              <div className="summary-card plagiarism" style={{ borderColor: getPlagiarismColor(results.plagiarismPercentage) }}>
                <div className="summary-icon" style={{ color: getPlagiarismColor(results.plagiarismPercentage) }}>
                  <FontAwesomeIcon icon="fas fa-exclamation-triangle" />
                </div>
                <div className="summary-content">
                  <div className="summary-percentage" style={{ color: getPlagiarismColor(results.plagiarismPercentage) }}>
                    {results.plagiarismPercentage}%
                  </div>
                  <div className="summary-label">Plagiarized</div>
                  <div className="summary-status" style={{ color: getPlagiarismColor(results.plagiarismPercentage) }}>
                    {getPlagiarismStatus(results.plagiarismPercentage)}
                  </div>
                </div>
              </div>
            </div>

            {/* Sources Found */}
            {results.sources.length > 0 && (
              <div className="sources-section">
                <h4 className="sources-title">
                  <FontAwesomeIcon icon="fas fa-link" className="title-icon" />
                  Similar Sources Found ({results.sources.length})
                </h4>
                <div className="sources-list">
                  {results.sources.map((source, index) => (
                    <div key={index} className="source-item">
                      <div className="source-header">
                        <h5 className="source-title">{source.title}</h5>
                        <span className="source-similarity" style={{ color: getPlagiarismColor(source.similarity) }}>
                          {source.similarity}% similar
                        </span>
                      </div>
                      <p className="source-snippet">{source.snippet}</p>
                      <a href={source.url} target="_blank" rel="noopener noreferrer" className="source-link">
                        <FontAwesomeIcon icon="fas fa-external-link-alt" />
                        View Source
                      </a>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Suggestions */}
            <div className="suggestions-section">
              <h4 className="suggestions-title">
                <FontAwesomeIcon icon="fas fa-lightbulb" className="title-icon" />
                Improvement Suggestions
              </h4>
              <div className="suggestions-list">
                {results.suggestions.map((suggestion, index) => (
                  <div key={index} className="suggestion-item">
                    <FontAwesomeIcon icon="fas fa-arrow-right" className="suggestion-icon" />
                    <span className="suggestion-text">{suggestion}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Tool Information */}
      <div style={{ 
        backgroundColor: 'var(--bg-card)', 
        border: '1px solid var(--border)', 
        borderRadius: '1rem', 
        padding: '2rem',
        marginTop: '2rem'
      }}>
        <h3 style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>
          <FontAwesomeIcon icon="fas fa-info-circle" style={{ marginRight: '0.5rem', color: 'var(--accent)' }} />
          About Plagiarism Detection
        </h3>
        
        <div style={{ color: 'var(--text-secondary)', lineHeight: '1.6' }}>
          <h4 style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>Frequently Asked Questions</h4>
          
          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How does the Plagiarism Checker work?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our Plagiarism Checker uses advanced text-matching algorithms to compare your content 
              against millions of web pages, academic databases, and published works. It identifies 
              similar phrases, sentences, and passages, then provides detailed reports showing 
              originality percentages, source matches, and specific suggestions for improvement. 
              The tool analyzes text structure, word patterns, and semantic similarities.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What percentage of plagiarism is acceptable?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Generally, less than 10% similarity is considered excellent, 10-25% is acceptable 
              with proper citations, and above 25% may indicate significant plagiarism concerns. 
              However, acceptable levels vary by institution and context. Academic papers typically 
              require higher originality than blog posts. Always check with your specific guidelines 
              and ensure proper attribution for any matched content.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Is my text stored or shared when using this tool?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              No, your text is processed securely and is never stored on our servers or shared 
              with third parties. All plagiarism checking happens locally in your browser, 
              ensuring complete privacy and security for your sensitive content. This makes 
              it safe to use with confidential documents, unpublished work, and proprietary content.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What types of sources does the checker scan?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our checker scans web pages, academic databases, published articles, research papers, 
              books, and other publicly available content. It identifies matches from various sources 
              including websites, academic journals, news articles, and educational materials. 
              The tool provides source URLs and titles when matches are found, helping you 
              identify where similar content exists.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How accurate is the plagiarism detection?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our plagiarism checker provides high accuracy in detecting similarities and matches. 
              However, like all automated tools, it may occasionally flag common phrases or 
              technical terms as matches. The tool is designed to identify potential issues 
              rather than make final judgments. Always review flagged content manually and 
              consider context when interpreting results.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What should I do if plagiarism is detected?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              If plagiarism is detected: review the flagged sections carefully, add proper 
              citations for quoted or paraphrased content, rewrite sections that are too similar, 
              use quotation marks for direct quotes, and ensure your work adds original value 
              and analysis. The tool provides specific suggestions for each detected issue 
              to help you improve your content.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Can I use this tool for academic submissions?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Yes, you can use this tool to check academic work before submission. However, 
              always verify results with your institution's official plagiarism detection 
              system if required. Use this tool as a preliminary check to identify potential 
              issues and improve your work before final submission. Different institutions 
              may use different databases and detection methods.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What's the difference between plagiarism and proper citation?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Plagiarism occurs when you use someone else's work without proper attribution. 
              Proper citation involves acknowledging sources through quotes, paraphrasing with 
              attribution, and including references. The checker helps identify uncredited 
              similarities, but you must determine whether they require citations based on 
              academic standards and your specific context.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How can I avoid plagiarism in my writing?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              To avoid plagiarism: always cite sources properly, use quotation marks for 
              direct quotes, paraphrase ideas in your own words with attribution, develop 
              original arguments and analysis, keep track of all sources during research, 
              and use plagiarism checkers as a final verification step. When in doubt, 
              err on the side of over-citing rather than under-citing.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              Can the checker detect paraphrasing plagiarism?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Our checker can detect some forms of paraphrasing plagiarism, especially when 
              the structure and key phrases remain similar. However, sophisticated paraphrasing 
              that changes wording while maintaining the same ideas may be harder to detect. 
              The tool works best with direct copying and obvious similarities. Always ensure 
              your paraphrasing includes proper attribution and adds original analysis.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              What are the legal implications of plagiarism?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Plagiarism can have serious consequences including academic penalties, loss of 
              credibility, legal issues with copyright infringement, and professional repercussions. 
              In academic settings, it can result in failing grades, suspension, or expulsion. 
              In professional contexts, it can damage reputation and lead to legal action. 
              Always ensure your work is original and properly attributed.
            </p>
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <h5 style={{ marginBottom: '0.5rem', color: 'var(--text-primary)', fontWeight: '600' }}>
              How often should I check my work for plagiarism?
            </h5>
            <p style={{ marginBottom: '1rem' }}>
              Check your work for plagiarism: before submitting academic assignments, before 
              publishing blog posts or articles, when working on important documents, after 
              major revisions, and as part of your final review process. Regular checking 
              helps you develop better writing habits and catch issues early. Consider 
              checking longer documents in sections for more detailed analysis.
            </p>
          </div>
        </div>
      </div>

      {/* How to Use */}
      <div className="how-to-card">
        <h3 className="how-to-title">
          <FontAwesomeIcon icon="fas fa-play-circle" className="title-icon" />
          How to Use Plagiarism Checker
        </h3>
        <div className="steps-list">
          <div className="step">
            <div className="step-number">1</div>
            <div className="step-content">
              <h4>Enter Your Text</h4>
              <p>Paste or type your text into the input field. Minimum 50 characters required for accurate detection.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">2</div>
            <div className="step-content">
              <h4>Start the Check</h4>
              <p>Click "Check Plagiarism" to begin the analysis. The process typically takes 2-3 seconds.</p>
            </div>
          </div>
          <div className="step">
            <div className="step-number">3</div>
            <div className="step-content">
              <h4>Review Results</h4>
              <p>Examine the originality percentage, similar sources, and improvement suggestions provided.</p>
            </div>
          </div>
        </div>
      </div>

      {/* Features */}
      <div className="features-card">
        <h3 className="features-title">
          <FontAwesomeIcon icon="fas fa-star" className="title-icon" />
          Key Features
        </h3>
        <div className="features-grid">
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-shield-alt" className="feature-icon" />
            <h4>Privacy Protected</h4>
            <p>Your text is processed securely and never stored on our servers</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-search" className="feature-icon" />
            <h4>Comprehensive Scan</h4>
            <p>Checks against millions of web pages and academic databases</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-chart-bar" className="feature-icon" />
            <h4>Detailed Reports</h4>
            <p>Provides originality percentage, sources, and improvement suggestions</p>
          </div>
          <div className="feature">
            <FontAwesomeIcon icon="fas fa-download" className="feature-icon" />
            <h4>Export Options</h4>
            <p>Download detailed reports or copy results to clipboard</p>
          </div>
        </div>
      </div>

      {/* Use Cases */}
      <div className="use-cases-card">
        <h3 className="use-cases-title">
          <FontAwesomeIcon icon="fas fa-lightbulb" className="title-icon" />
          Popular Use Cases
        </h3>
        <div className="use-cases-grid">
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-graduation-cap" className="use-case-icon" />
            <h4>Academic Writing</h4>
            <p>Check essays, research papers, and assignments for originality</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-blog" className="use-case-icon" />
            <h4>Content Creation</h4>
            <p>Verify blog posts, articles, and web content originality</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-book" className="use-case-icon" />
            <h4>Publishing</h4>
            <p>Ensure manuscripts and books are original before publication</p>
          </div>
          <div className="use-case">
            <FontAwesomeIcon icon="fas fa-briefcase" className="use-case-icon" />
            <h4>Professional Work</h4>
            <p>Check reports, proposals, and business documents</p>
          </div>
        </div>
      </div>

      <style jsx>{`
        .tool-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 2rem;
          display: flex;
          flex-direction: column;
          gap: 2rem;
        }

        .tool-card {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          border-radius: 24px;
          padding: 2rem;
          color: white;
          box-shadow: 0 20px 40px rgba(0,0,0,0.1);
          position: relative;
          overflow: hidden;
        }

        .tool-card::before {
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><pattern id="grain" width="100" height="100" patternUnits="userSpaceOnUse"><circle cx="50" cy="50" r="1" fill="white" opacity="0.1"/></pattern></defs><rect width="100" height="100" fill="url(%23grain)"/></svg>');
          opacity: 0.3;
        }

        .tool-header {
          display: flex;
          align-items: center;
          gap: 1rem;
          margin-bottom: 2rem;
          position: relative;
          z-index: 1;
        }

        .tool-icon {
          font-size: 2.5rem;
          opacity: 0.9;
        }

        .tool-title-section {
          flex: 1;
        }

        .tool-title {
          font-size: 2rem;
          font-weight: 700;
          margin: 0;
          text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }

        .tool-subtitle {
          font-size: 1.1rem;
          margin: 0.5rem 0 0 0;
          opacity: 0.9;
          font-weight: 300;
        }

        .input-section {
          position: relative;
          z-index: 1;
          margin-bottom: 2rem;
        }

        .input-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
        }

        .input-label {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-weight: 600;
          font-size: 1rem;
        }

        .label-icon {
          opacity: 0.8;
        }

        .text-stats {
          display: flex;
          gap: 1rem;
        }

        .stat-item {
          display: flex;
          align-items: center;
          gap: 0.25rem;
          font-size: 0.9rem;
          opacity: 0.8;
        }

        .text-input {
          width: 100%;
          padding: 1rem;
          border: 2px solid rgba(255,255,255,0.2);
          border-radius: 12px;
          background: rgba(255,255,255,0.1);
          color: white;
          font-size: 1rem;
          line-height: 1.6;
          resize: vertical;
          min-height: 200px;
          backdrop-filter: blur(10px);
          transition: all 0.3s ease;
        }

        .text-input:focus {
          outline: none;
          border-color: rgba(255,255,255,0.5);
          background: rgba(255,255,255,0.15);
        }

        .text-input::placeholder {
          color: rgba(255,255,255,0.7);
        }

        .input-footer {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-top: 1rem;
        }

        .requirements {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-size: 0.9rem;
          opacity: 0.8;
        }

        .btn-primary {
          background: linear-gradient(45deg, #ff6b6b, #ee5a24);
          border: none;
          border-radius: 12px;
          padding: 1rem 2rem;
          color: white;
          font-weight: 600;
          font-size: 1rem;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          transition: all 0.3s ease;
          box-shadow: 0 4px 15px rgba(255,107,107,0.4);
        }

        .btn-primary:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 6px 20px rgba(255,107,107,0.6);
        }

        .btn-primary:disabled {
          opacity: 0.6;
          cursor: not-allowed;
          transform: none;
        }

        .btn-secondary {
          background: rgba(255,255,255,0.2);
          border: 2px solid rgba(255,255,255,0.3);
          border-radius: 12px;
          padding: 0.75rem 1.5rem;
          color: white;
          font-weight: 600;
          font-size: 0.9rem;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          transition: all 0.3s ease;
          backdrop-filter: blur(10px);
        }

        .btn-secondary:hover {
          background: rgba(255,255,255,0.3);
          border-color: rgba(255,255,255,0.5);
        }

        .results-section {
          margin-top: 2rem;
          position: relative;
          z-index: 1;
        }

        .results-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
        }

        .results-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          font-size: 1.25rem;
          font-weight: 600;
        }

        .title-icon {
          opacity: 0.8;
        }

        .results-actions {
          display: flex;
          gap: 0.75rem;
        }

        .plagiarism-summary {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 1.5rem;
          margin-bottom: 2rem;
        }

        .summary-card {
          background: rgba(255,255,255,0.1);
          border-radius: 16px;
          padding: 1.5rem;
          text-align: center;
          backdrop-filter: blur(10px);
          border: 2px solid rgba(255,255,255,0.2);
        }

        .summary-card.originality {
          border-color: #10b981;
        }

        .summary-icon {
          font-size: 2rem;
          margin-bottom: 1rem;
        }

        .summary-card.originality .summary-icon {
          color: #10b981;
        }

        .summary-percentage {
          font-size: 2.5rem;
          font-weight: 700;
          margin-bottom: 0.5rem;
        }

        .summary-label {
          font-size: 1rem;
          font-weight: 500;
          margin-bottom: 0.5rem;
        }

        .summary-status {
          font-size: 0.9rem;
          font-weight: 600;
        }

        .sources-section, .suggestions-section {
          margin-bottom: 2rem;
        }

        .sources-title, .suggestions-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          font-size: 1.1rem;
          font-weight: 600;
          margin-bottom: 1rem;
        }

        .sources-list {
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        .source-item {
          background: rgba(255,255,255,0.1);
          border-radius: 12px;
          padding: 1.5rem;
          backdrop-filter: blur(10px);
        }

        .source-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
        }

        .source-title {
          font-size: 1rem;
          font-weight: 600;
          margin: 0;
        }

        .source-similarity {
          font-size: 0.9rem;
          font-weight: 600;
        }

        .source-snippet {
          color: rgba(255,255,255,0.8);
          line-height: 1.6;
          margin-bottom: 1rem;
        }

        .source-link {
          color: #4ecdc4;
          text-decoration: none;
          font-size: 0.9rem;
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }

        .source-link:hover {
          text-decoration: underline;
        }

        .suggestions-list {
          display: flex;
          flex-direction: column;
          gap: 0.75rem;
        }

        .suggestion-item {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          background: rgba(255,255,255,0.1);
          border-radius: 8px;
          padding: 1rem;
          backdrop-filter: blur(10px);
        }

        .suggestion-icon {
          color: #feca57;
          font-size: 0.9rem;
        }

        .suggestion-text {
          color: rgba(255,255,255,0.9);
        }

        .info-card, .how-to-card, .features-card, .use-cases-card {
          background: var(--bg-card);
          border: 1px solid var(--border);
          border-radius: 16px;
          padding: 2rem;
          box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }

        .info-title, .how-to-title, .features-title, .use-cases-title {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          margin-bottom: 1.5rem;
          color: var(--text-primary);
          font-size: 1.25rem;
          font-weight: 600;
        }

        .title-icon {
          color: var(--accent);
        }

        .info-content {
          color: var(--text-secondary);
          line-height: 1.7;
        }

        .info-content p {
          margin-bottom: 1rem;
        }

        .steps-list {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .step {
          display: flex;
          gap: 1rem;
          align-items: flex-start;
        }

        .step-number {
          background: linear-gradient(45deg, var(--accent), #667eea);
          color: white;
          width: 32px;
          height: 32px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 600;
          font-size: 0.9rem;
          flex-shrink: 0;
        }

        .step-content h4 {
          margin: 0 0 0.5rem 0;
          color: var(--text-primary);
          font-size: 1rem;
        }

        .step-content p {
          margin: 0;
          color: var(--text-secondary);
          line-height: 1.6;
        }

        .features-grid, .use-cases-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 1.5rem;
        }

        .feature, .use-case {
          text-align: center;
          padding: 1.5rem;
          border-radius: 12px;
          background: var(--bg-secondary);
          border: 1px solid var(--border);
          transition: all 0.3s ease;
        }

        .feature:hover, .use-case:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 25px rgba(0,0,0,0.1);
        }

        .feature-icon, .use-case-icon {
          font-size: 2rem;
          color: var(--accent);
          margin-bottom: 1rem;
        }

        .feature h4, .use-case h4 {
          margin: 0 0 0.75rem 0;
          color: var(--text-primary);
          font-size: 1rem;
        }

        .feature p, .use-case p {
          margin: 0;
          color: var(--text-secondary);
          font-size: 0.9rem;
          line-height: 1.5;
        }

        @media (max-width: 768px) {
          .tool-container {
            padding: 1rem;
          }
          
          .input-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }
          
          .results-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }
          
          .results-actions {
            flex-wrap: wrap;
          }
          
          .plagiarism-summary {
            grid-template-columns: 1fr;
          }
          
          .source-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 0.5rem;
          }
        }
      `}</style>
    </div>
  )
}

export default PlagiarismChecker

